---
kind: Pod
apiVersion: v1
metadata:
  name: test-app
spec:
  containers:
    - name: test
      image: busybox 
      volumeMounts:
        - mountPath: "/data"
          name: chfs
      command: ["sleep", "1000000"]
  volumes:
    - name: chfs
      csi:
        driver: chfs.csi.k8s.io
        volumeAttributes:
          server: "ofi+sockets://172.17.0.2:35347"
